### ISSUE TITLE
tests do not run on installed gdxpds

### ISSUE THREAD

**Issue by elainethale** [NREL/gdx-pandas#22]
nosetests finds the tests to run, but on Python 3 they give:

```
C:\Users\ehale>nosetests gdxpds
EEEEE.
======================================================================
ERROR: gdxpds.test.test_conversions.test_gdx_roundtrip
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_gdx_roundtrip() missing 1 required positional argument: 'manage_
rundir'

======================================================================
ERROR: gdxpds.test.test_conversions.test_csv_roundtrip
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_csv_roundtrip() missing 1 required positional argument: 'manage_
rundir'

======================================================================
ERROR: gdxpds.test.test_details.test_roundtrip_just_special_values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_roundtrip_just_special_values() missing 1 required positional ar
gument: 'manage_rundir'

======================================================================
ERROR: gdxpds.test.test_details.test_roundtrip_special_values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_roundtrip_special_values() missing 1 required positional argumen
t: 'manage_rundir'

======================================================================
ERROR: gdxpds.test.test_details.test_from_scratch_sets
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_from_scratch_sets() missing 1 required positional argument: 'man
age_rundir'

----------------------------------------------------------------------
Ran 6 tests in 0.062s

FAILED (errors=5)
```

And on Python 2:

```
C:\Users\ehale>C:\Python27\Scripts\nosetests.exe gdxpds
EEEEE.
======================================================================
ERROR: gdxpds.test.test_conversions.test_gdx_roundtrip
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_gdx_roundtrip() takes exactly 1 argument (0 given)
-------------------- >> begin captured logging << --------------------
gdxpds: INFO: Optional package psutil not found. pip install psutil if you would
 like to monitor memory usage.
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: gdxpds.test.test_conversions.test_csv_roundtrip
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_csv_roundtrip() takes exactly 1 argument (0 given)

======================================================================
ERROR: gdxpds.test.test_details.test_roundtrip_just_special_values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_roundtrip_just_special_values() takes exactly 1 argument (0 give
n)

======================================================================
ERROR: gdxpds.test.test_details.test_roundtrip_special_values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_roundtrip_special_values() takes exactly 1 argument (0 given)

======================================================================
ERROR: gdxpds.test.test_details.test_from_scratch_sets
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_from_scratch_sets() takes exactly 1 argument (0 given)

----------------------------------------------------------------------
Ran 6 tests in 0.063s

FAILED (errors=5)
```

**Comment by elainethale** [comment]
Moved over to pytest, but pytest does not find installed gdxpds to test, at least not with 

```
pytest gdxpds
```

**Comment by elainethale** [comment]
Just run

```
pytest --pyargs gdxpds
```

**Comment by elainethale** [comment]
Updated README accordingly.
